"""Adding api_credits collumn to users

Revision ID: 124d5760dabd
Revises: 57e01117a156
Create Date: 2025-03-31 20:16:00.689029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124d5760dabd'
down_revision: Union[str, None] = '57e01117a156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_credits', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_credits')
    # ### end Alembic commands ###
