"""Adding suffix to APIKey Model

Revision ID: 57e01117a156
Revises: 66f0eb1a1f56
Create Date: 2025-03-31 19:21:50.182253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e01117a156'
down_revision: Union[str, None] = '66f0eb1a1f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('suffix', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'suffix')
    # ### end Alembic commands ###
